# Generated by Django 5.1.6 on 2025-02-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
